// Emits static/grammar.js from browser.ts (grammar + registry + render) so
// the webview shares the exact parser, widget mapping and input descriptors.
// Run: deno task build:grammar
// Transpiled with esbuild (pinned) — no hand-rolled type stripping.
// A sha256 staleness hash is embedded; tests/grammar_test.ts fails when
// grammar.ts, registry.ts or render.ts change without regenerating.
import { dirname, join } from "std/path";

const ESBUILD_VERSION = "0.25.0";

const dir = new URL(".", import.meta.url).pathname.replace(/^\//, "");
const appRoot = join(dir, "..");

async function ensureEsbuild(tmp: string): Promise<string> {
  const exe = join(tmp, "node_modules", ".bin", Deno.build.os === "windows" ? "esbuild.cmd" : "esbuild");
  try {
    await Deno.stat(exe);
    return exe;
  } catch {
    // fall through to install
  }
  const npm = new Deno.Command(Deno.build.os === "windows" ? "npm.cmd" : "npm", {
    args: ["install", "--no-save", "--no-audit", "--no-fund", `esbuild@${ESBUILD_VERSION}`],
    cwd: tmp,
    stdout: "piped",
    stderr: "piped",
  });
  const r = await npm.output();
  if (!r.success) throw new Error(new TextDecoder().decode(r.stderr));
  return exe;
}

const tmp = await Deno.makeTempDir();
try {
  const esbuild = await ensureEsbuild(tmp);
  const entry = join(appRoot, "browser.ts");
  const bundle = join(tmp, "grammar.bundle.js");
  const proc = new Deno.Command(esbuild, {
    args: [entry, "--bundle", "--format=iife", "--global-name=CCGrammarSrc", "--target=es2017", `--outfile=${bundle}`],
    cwd: appRoot,
    stdout: "piped",
    stderr: "piped",
  });
  const r = await proc.output();
  if (!r.success) throw new Error(new TextDecoder().decode(r.stderr));
  let body = await Deno.readTextFile(bundle);
  // esbuild IIFE assigns to CCGrammarSrc — re-export onto window.CCGrammar.
  const hashBuf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(body));
  const hash = [...new Uint8Array(hashBuf)].map((b) => b.toString(16).padStart(2, "0")).join("");
  const emitted = `// GENERATED by scripts/build-grammar.ts — do not hand-edit.
// Regenerate: deno task build:grammar. Source hash: ${hash}
${body}
window.CCGrammar = Object.assign({ GRAMMAR_HASH: "${hash}" }, window.CCGrammarSrc);
`;
  const outPath = join(appRoot, "static", "grammar.js");
  await Deno.mkdir(dirname(outPath), { recursive: true });
  await Deno.writeTextFile(outPath, emitted);
  console.log("Wrote", outPath, emitted.length, "bytes, hash", hash.slice(0, 12));
} finally {
  await Deno.remove(tmp, { recursive: true });
}
